import clubs2 from '../Images/Deck/clubs-2.png'
import clubs3 from '../Images/Deck/clubs-3.png'
import clubs4 from '../Images/Deck/clubs-4.png'
import clubs5 from '../Images/Deck/clubs-5.png'
import clubs6 from '../Images/Deck/clubs-6.png'
import clubs7 from '../Images/Deck/clubs-7.png'
import clubs8 from '../Images/Deck/clubs-8.png'
import clubs9 from '../Images/Deck/clubs-9.png'
import clubs10 from '../Images/Deck/clubs-10.png'
import clubsJ from '../Images/Deck/clubs-jack.png'
import clubsQ from '../Images/Deck/clubs-queen.png'
import clubsK from '../Images/Deck/clubs-king.png'
import clubsA from '../Images/Deck/clubs-ace.png'
import spades2 from '../Images/Deck/spades-2.png'
import spades3 from '../Images/Deck/spades-3.png'
import spades4 from '../Images/Deck/spades-4.png'
import spades5 from '../Images/Deck/spades-5.png'
import spades6 from '../Images/Deck/spades-6.png'
import spades7 from '../Images/Deck/spades-7.png'
import spades8 from '../Images/Deck/spades-8.png'
import spades9 from '../Images/Deck/spades-9.png'
import spades10 from '../Images/Deck/spades-10.png'
import spadesJ from '../Images/Deck/spades-jack.png'
import spadesQ from '../Images/Deck/spades-queen.png'
import spadesK from '../Images/Deck/spades-king.png'
import spadesA from '../Images/Deck/spades-ace.png'
import hearts2 from '../Images/Deck/hearts-2.png'
import hearts3 from '../Images/Deck/hearts-3.png'
import hearts4 from '../Images/Deck/hearts-4.png'
import hearts5 from '../Images/Deck/hearts-5.png'
import hearts6 from '../Images/Deck/hearts-6.png'
import hearts7 from '../Images/Deck/hearts-7.png'
import hearts8 from '../Images/Deck/hearts-8.png'
import hearts9 from '../Images/Deck/hearts-9.png'
import hearts10 from '../Images/Deck/hearts-10.png'
import heartsJ from '../Images/Deck/hearts-jack.png'
import heartsQ from '../Images/Deck/hearts-queen.png'
import heartsK from '../Images/Deck/hearts-king.png'
import heartsA from '../Images/Deck/hearts-ace.png'
import diamonds2 from '../Images/Deck/hearts-2.png'
import diamonds3 from '../Images/Deck/diamonds-3.png'
import diamonds4 from '../Images/Deck/diamonds-4.png'
import diamonds5 from '../Images/Deck/diamonds-5.png'
import diamonds6 from '../Images/Deck/diamonds-6.png'
import diamonds7 from '../Images/Deck/diamonds-7.png'
import diamonds8 from '../Images/Deck/diamonds-8.png'
import diamonds9 from '../Images/Deck/diamonds-9.png'
import diamonds10 from '../Images/Deck/diamonds-10.png'
import diamondsJ from '../Images/Deck/diamonds-jack.png'
import diamondsQ from '../Images/Deck/diamonds-queen.png'
import diamondsK from '../Images/Deck/diamonds-king.png'
import diamondsA from '../Images/Deck/diamonds-ace.png'

const Cards = {
    clubs2, clubs3, clubs4, clubs5, clubs6, clubs7, clubs8, clubs9, clubs10, clubsJ, clubsQ, clubsK, clubsA, spades2, spades3, spades4, spades5, spades6, spades7, spades8, spades9, spades10, spadesJ, spadesQ, spadesK, spadesA, hearts2, hearts3, hearts4, hearts5, hearts6, hearts7, hearts8, hearts9, hearts10, heartsJ, heartsQ, heartsK, heartsA, diamonds2, diamonds3, diamonds4, diamonds5, diamonds6, diamonds7, diamonds8, diamonds9, diamonds10, diamondsJ, diamondsQ, diamondsK, diamondsA,
}


export default Cards